### ISSUE TITLE
Database issue when deleting from Levels Table

### ISSUE THREAD

**Issue by WeirdBalls** [ICT2101-2201-P5-1/CoolMotor#10]
`Error Code: 1451. Cannot delete or update a parent row: a foreign key constraint fails (cool_motor.dashboard, CONSTRAINT map_id FOREIGN KEY (map_id) REFERENCES levels (map_id) ON DELETE RESTRICT ON UPDATE RESTRICT)
`
This error pops up when trying to delete entries from the database using the mysql workbench. It either shows this error or it  times out.

**Comment by BestCrochet** [comment]
I am having this same issue. I realised this is because of the Database structure.
The foreign key 'map_id' in the Dashboard table should be ON DELETE CASCADE, instead of ON DELETE RESTRICT.

I will update this key.

![image](https://user-images.githubusercontent.com/66672755/142381510-c53e0edc-b003-4924-b32a-489d92d36170.png)

**Comment by BestCrochet** [comment]
Btw I seem to have trouble connecting to the DB to update this key.
Can @ShawnLemuelDabi check the DB connection on AWS side?

![image](https://user-images.githubusercontent.com/66672755/142381612-1b891c9c-7600-4ac1-8b9a-061c06de3ed7.png)

**Comment by mayinot** [comment]
@ShawnLemuelDabi Please try to fix this issue on the remote database. You can consider creating a new database.

**Comment by ShawnLemuelDabi** [comment]
ok. Looking into it✌️

**Comment by ShawnLemuelDabi** [comment]
Hi all, I have re-established the DB. Please do check and let me know if all your functions work properly

Regards,
Shawn
